config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"

  # get '/', to: "home#index"
  get 'about', to: "home#about"
  get 'terms', to: "home#terms"

  resource :contacts, only: [:new, :create], path_names: { new: '' }
  resources :articles do 
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  has_many :comments, dependent: :destroy
  before_destroy :delete_comments

  def subject
    title
  end

  def last_comment
    comments.last
  end

  private

  def delete_comments
    comments.destroy_all
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end


  def show
    @article = Article.find(params[:id])
  end
  
  def edit
    @article = Article.find(params[:id])
  end


  def new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      
      redirect_to @article
      # render action: "show"
    else
      render action: "new"
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render action: "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @article = Article.find(params[:article_id])
    comments = @article.comments.new(comment_params)
    comments.author = current_user.username
    comments.save

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
 
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # before_action :authenticate_user!

  def new
    # @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      @contact.save
    else
      render action: "new"
    end
  end

  private

  # Метод задающий параметры для контактов
  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!

  def index
    @welcome = "Добро пожаловать"
  end

  def about
    @about = "О сайте"
  end

  def terms
    @terms = "Пользовательское соглашение"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/articles/edit.html.erb
<h2>Редактирование</h2>
<!-- Форма для редактирования -->
<%= form_for :article, url: article_path(@article), method: :put do |f| %>
  <% if @article && @article.errors.any? %>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<h1>Все статьи на сайте</h1>
<p><%= link_to "Create new article", new_article_path, class: 'btn btn-primary btn-lg' %></p>
<!-- Выводим список статей -->
<% @articles.order(created_at: :desc).each do |article| %>
  <div class="card mb-3">
    <div class="card-header">
      <h5><%= article.title %></h5>
    </div>
    <div class="card-body">
      <div class="card-text"><%= simple_format(article.body) %></div>
      <!-- Кнопки для редактирования и удаления -->
      <div class="d-inline-flex gap-2">
        <%= link_to "Show", article_path(article), class: 'btn btn-primary' %>
        <%= link_to "Edit", edit_article_path(article), class: 'btn btn-success'%>
        <%= button_to "Delete", article_path(article), class: 'btn btn-danger', method: :delete %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<h2>Создать статью</h2>
<!-- Форма для создания Статьи -->
<%= form_for :article, url: articles_path do |f| %>
  <% if @article && @article.errors.any? %>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<%= link_to 'Show all articles', articles_path, class: 'btn btn-primary btn-lg' %>
<hr>
<h4><%= @article.title %></h4>
<p><%= simple_format(@article.body) %></p>
<%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary btn-sm" %>
<hr>
<!-- <a href="/articles">Show all articles</a><br> -->
<!-- Форма создания коментария -->
<%= form_for([@article, @article.comments.build]) do |f| %>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>
<hr>
<!-- Список коментариев -->
<% @article.comments.order(created_at: :desc).each do |comment| %>
  <p><%= simple_format(comment.body) %></p>
  <%= comment.author %> | <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  <hr>
<% end %>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<%= @contact.email %><br>
<%= @contact.message %>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>
<%= form_for :contact, url: contacts_path do |f| %>
  <% if @contact && @contact.errors.any? %>
    <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :email %><br>
  <%= f.text_field :email%><br>
  <%= f.label :message %><br>
  <%= f.text_area :message %><br>
  <%= f.submit 'Send message'%>
<% end %>

app/views/home/about.html.erb
<h1> About </h1>
<p> <%= @about %> </p>

app/views/home/index.html.erb
<h1>Начальная страница 1</h1>
<p> <%= @welcome %> </p>

app/views/home/terms.html.erb
<h1> Terms </h1>
<p> <%= @terms %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Блог Rails 6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
          crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
            crossorigin="anonymous"></script>
  </head>
  <!-- Основная часть страницы, шаблон для всех страниц -->
  <body>
    <div class="container">
      <!-- Навигация -->
      <nav class="navbar">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Главная</a>
          <%= link_to "Articles", articles_path, class: "nav-link" %>
          <%= link_to "Contact", contacts_path, class: "nav-link" %>
          <!-- <%= link_to "Terms", terms_path, class: "nav-link" %> -->
          <!-- <%= link_to "About", about_path, class: "nav-link" %> -->
          <!-- Авторизация или выход -->
          <% if user_signed_in? %>
            Hello, <%= current_user.username %> <%= button_to "Sign out", destroy_user_session_path, class: "nav-link", method: :delete %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          <% end %>
        </div>
      </nav>
      <!-- Вставка других страниц содержимого -->
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>